name: Generate pdf
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://kauplan/review2.5
      - run: docker run --rm -v $PWD:/work -w /work kauplan/review2.5 rake pdf
      - name: Get Repository Name
        id: Repository
        run: echo ::set-output name=name::${GITHUB_REPOSITORY##*/}
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ steps.Repository.outputs.name }}
          path: ${{ steps.Repository.outputs.name }}.pdf
